
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        exclude: uv\.lock
      - id: check-merge-conflict
      - id: check-toml
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: mixed-line-ending

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      - id: ruff
        args:
          [
            --fix,
            --exit-non-zero-on-fix
          ]
      - id: ruff-format
        args: ["--exit-non-zero-on-format"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args:
          [
            "-c",
            "pyproject.toml",
            "--severity-level",
            "medium",
            "-x",
            "tests",
          ]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        additional_dependencies: [
          "pyarrow-stubs",
          "pandas-stubs",
          "types-PyYAML",
          "types-requests",
        ]
        args: [
          --config-file=pyproject.toml,
          --strict,
          --ignore-missing-imports,
          --explicit-package-bases,
          --disable-error-code=misc
        ]

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.14
    hooks:
      - id: vulture
        args: [
          "agents/",
          "mcp-servers/",
          "--min-confidence", "80",
        ]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.4
    hooks:
      - id: check-github-workflows
        files: ^\.github/workflows/
      - id: check-dependabot
