x-aws-env: &aws_env
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
  AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-}
  AWS_SECURITY_TOKEN: ${AWS_SECURITY_TOKEN:-}
  AWS_REGION: ${AWS_REGION:-}
  AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-}

services:
  mcp-server:
    build:
      context: ../..
      dockerfile: docker/voc/server.Dockerfile
    image: mcp-server:latest
    env_file:
      - ../../.env
    environment:
      <<: *aws_env
      AZURE_OPENAI_API_VERSION: ${AZURE_OPENAI_API_VERSION:-2024-12-01-preview}
    ports:
      - "9000:9000"
    volumes:
      - ../docker-volume:/app/downloads
      - ../../.env:/app/.env:ro
    restart: unless-stopped

  audio-processing:
    build: &agent-build
      context: ../..
      dockerfile: docker/voc/agent.Dockerfile
    image: audio-processing-agent:latest
    command: ["sh", "-c", "set -a && . /app/.env && set +a && python -m voc_agent.audio_processing.__main__"]
    env_file:
      - ../../.env
    environment:
      <<: *aws_env
      AUDIO_PROCESSING_HOST: 0.0.0.0
      AUDIO_PROCESSING_PORT: 10001
      AUDIO_PROCESSING_PUBLIC_HOST: audio-processing
      AZURE_OPENAI_API_VERSION: ${AZURE_OPENAI_API_VERSION:-2024-12-01-preview}
      LANGFUSE_HOST: ${LANGFUSE_HOST:-https://langfuse.data.socar.me}
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY:-}
      LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY:-}
      LANGFUSE_RELEASE: ${LANGFUSE_RELEASE:-}
      LANGFUSE_ENVIRONMENT: ${LANGFUSE_ENVIRONMENT:-}
      STT_MCP_SSE_URL: http://mcp-server:9000/sse

    ports:
      - "10001:10001"
    volumes:
      - ../../.env:/app/.env:ro
    restart: unless-stopped
    depends_on:
      - mcp-server

  consultation-analysis:
    build: *agent-build
    image: consultation-analysis-agent:latest
    command: ["sh", "-c", "set -a && . /app/.env && set +a && python -m voc_agent.consultation_analysis.__main__"]
    env_file:
      - ../../.env
    environment:
      <<: *aws_env
      CONSULTATION_ANALYSIS_HOST: 0.0.0.0
      CONSULTATION_ANALYSIS_PORT: 10002
      CONSULTATION_ANALYSIS_PUBLIC_HOST: consultation-analysis
      AZURE_OPENAI_API_VERSION: ${AZURE_OPENAI_API_VERSION:-2024-12-01-preview}
      LANGFUSE_HOST: ${LANGFUSE_HOST:-https://langfuse.data.socar.me}
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY:-}
      LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY:-}
      LANGFUSE_RELEASE: ${LANGFUSE_RELEASE:-}
      LANGFUSE_ENVIRONMENT: ${LANGFUSE_ENVIRONMENT:-}
    ports:
      - "10002:10002"
    volumes:
      - ../../.env:/app/.env:ro
    restart: unless-stopped
    depends_on:
      - mcp-server

  orchestrator:
    build: *agent-build
    image: orchestrator-agent:latest
    command: ["sh", "-c", "set -a && . /app/.env && set +a && python -m voc_agent.orchestrator.__main__"]
    env_file:
      - ../../.env
    environment:
      <<: *aws_env
      ORCHESTRATOR_HOST: 0.0.0.0
      ORCHESTRATOR_PORT: 10000
      ORCHESTRATOR_PUBLIC_HOST: orchestrator
      AUDIO_PROCESSING_HOST: audio-processing
      AUDIO_PROCESSING_PORT: 10001
      AUDIO_PROCESSING_PUBLIC_HOST: audio-processing
      CONSULTATION_ANALYSIS_HOST: consultation-analysis
      CONSULTATION_ANALYSIS_PORT: 10002
      CONSULTATION_ANALYSIS_PUBLIC_HOST: consultation-analysis
      AZURE_OPENAI_API_VERSION: ${AZURE_OPENAI_API_VERSION:-2024-12-01-preview}
      LANGFUSE_HOST: ${LANGFUSE_HOST:-https://langfuse.data.socar.me}
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY:-}
      LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY:-}
      LANGFUSE_RELEASE: ${LANGFUSE_RELEASE:-}
      LANGFUSE_ENVIRONMENT: ${LANGFUSE_ENVIRONMENT:-}
    ports:
      - "10000:10000"
    volumes:
      - ../../.env:/app/.env:ro
    restart: unless-stopped
    depends_on:
      - mcp-server
      - audio-processing
      - consultation-analysis

  ui-for-simple-test:
    build:
      context: ../..
      dockerfile: docker/ui-for-simple-test.Dockerfile
    image: ui-for-simple-test:latest
    env_file:
      - ../../.env
    environment:
      ORCHESTRATOR_HOST: orchestrator
      ORCHESTRATOR_PORT: 10000
      RECOMMENDED_QUESTIONS: "다음 파일을 분석하고 어떤 내용인지 요약해줘 s3://socar-ai-aicc-audio-prod/47619241-161a-41a6-b69a-486da84815dc/year=2025/month=10/day=12/hour=14/conversation_id=0486ba65-af6a-44ed-8d09-324742ed6d10/, 쏘카가 뭐야?, AI Agent 프로젝트를 소개해줘., 쏘카에서 사용하는 기술 스택은 뭐야?, 피글렛은 실망했다."
    ports:
      - "3000:3000"
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - orchestrator

networks:
  default:
    name: voc-net
