[project]
name = "ui-for-simple-test"
version = "0.1.0"
description = "UI for simple test"
requires-python = ">=3.12"
dependencies = [
    "reflex==0.8.15",
    "httpx>=0.28.1",
    "a2a-sdk>=0.3.7",
    "pydantic>=2.11.9",
    "pydantic-settings>=2.0.0",
    "ai-common",
]

[tool.uv.sources]
ai-common = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["ui_for_simple_test"]
