[project]
name = "example-server"
version = "0.1.0"
description = "Example MCP Server"
requires-python = ">=3.12"
dependencies = [
    # 필요한 의존성을 여기에 추가
    # 예: "fastapi>=0.100.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
