[project]
name = "agent-common"
version = "0.1.0"
description = "Shared utilities for AI agents"
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
