[project]
name = "chat-analysis-mcp-server"
version = "0.1.0"
description = "MCP server for chat analysis system"
readme = "README.md"
requires-python = ">=3.12.11"
dependencies = [
    "loguru>=0.7.3",
    "fastmcp>=0.1.0",
]
