[project]
name = "example-agent"
version = "0.1.0"
description = "Example AI Agent"
requires-python = ">=3.12"
dependencies = [
    "ai-common",
]

[tool.uv.sources]
ai-common = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
