[project]
name = "voc-server"
version = "0.1.0"
description = "VOC 프로젝트용 MCP 서버"
requires-python = ">=3.12"
dependencies = [
    "ffmpeg>=1.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
